#!/usr/bin/python
# Rum Kist Racing NMEA2000 Logger
# Install script
# This is the real installer that does all the work
# Called from install-RKR-Logger

print '*** I am the main-install script ***' 

# Clean Exit
exit(0)

