#!/usr/bin/python
# Rum Kist Racing NMEA2000 Logger
# Install script
# This is the real installer that does all the work
# Called from install-RKR-Logger

# Required for parsing command line
import sys, getopt
# Required for http connection and download from Github
import requests
# Required for accessing O/S filesystem
import os
# Required for downloading files
import wget
# Required for chmod permissions
import stat


# Initialise installation messaging
verbose = True
def log(msg):
    if verbose:
        print msg
    return

log('*** Start main-install ***')

# Parse the arguments passed to the script
# If any of them are not recognised exit with an error
# Since this script downloads and runs the the main-install which might need more parameters
# it might be better if it did not terminate for unknown parameters and just leave that to the main installer.
# We can make that decision later.
try:
    opts, args = getopt.getopt(sys.argv[1:],"vg:",["verbose"])
except getopt.GetoptError as err:
    # Something went wrong, found an unexpected argument
    print (err)
    print 'Unexpected parameter - terminating main-install'
    exit(2)

gitHubURL = 'https://raw.githubusercontent.com/thetimmorland/rkr-logger/Dev-Bill/'

for opt, arg in opts:
    if opt == '-v':	
        verbose = True
        log('option -v')
        print '*********** -v'
    elif opt == '-g':
        gitHubURL = arg
        log('option -g')
        print '*********** -g'

directory = os.getcwd()

log('installing from ' + gitHubURL)
log('installing to ' + directory)

# download all the files listed in the manifest file
log('Retrieving manifest of files to install')
fileName = wget.download(gitHubURL + 'SetUp/manifest.txt', out=directory)
log('downloaded ' + fileName)
manifest = open('manifest.txt', 'r')
for source in manifest:
    fileName = wget.download(gitHubURL + source, out=directory)
    log('downloaded ' + fileName)

# install apt dependencies
log('Installing apt dependencies')
#rc = os.system('apt-get update')
#rc = os.system('apt-get install -y can-utils')

# modify /boot/config.txt
log('Modifying /boot/config')

log('*** Finish main-install')

# Clean Exit
exit(0)

